### ISSUE TITLE
Indexes and foreign keys

### ISSUE THREAD

**Issue by clouddra** [fnc12/sqlite_orm#10]
Hi,

Thanks for creating this library! It is intuitive and easy to use.
Just want to find out if there are any plans to add support for foreign keys and indexing?

**Comment by fnc12** [comment]
@clouddra hi. Thanks for the issue. I'm very pleased this code is useful.
Yes, there are plans to add support for foreign keys and indexes. Could you please help me: tell me how do you expect foreign keys and indexes to use (I mean are there any expectations about lib interface for this features). And please describe your use cases where you use `FOREIGN KEY` and `INDEX`.

1) My plans about foreign key - instead of 
`make_column("artist_id", &Song::artistId)` 
we'll have to write 
`make_column("artist_id", &Song::artistId, foreign_key(&Artist::id))`.

2) Plans about indexes are more abstract - right now I'm trying to understand how to do better: specify indexes statically (insert into `make_storage` a function `make_index` and create index in `sync_schema` if it doesn't exist just like table) or allow devs add indexes dynamically. What's your point? Thanks

**Comment by clouddra** [comment]
Thanks for the quick response.

1. That looks good
2. My use case will be more of the first scenario where indexes are defined statically. Theoretically I think that also allows devs to add index dynamically if I am not wrong. (devs can close, reopen the db and `sync_schema`)

**Comment by fnc12** [comment]
@clouddra now I'm thinking about adding `foreign key` feature to the lib. Firstly if schema has at least on foreign key lib the storage will call `PRAGMA foreign_keys = ON` after every `sqlite3_open`. It's ok. Second is `sync_schema`. Assume we call `sync_schema` when database doesn't exist at all. `sync_schema` will create every table in the order specified in `make_storage` call. It means during table creation any table that has column or table references to must be already created. This means that tables must be provided in order with increasing dependencies. Otherwise error occurs.
Another case is tables with cross-references. For example: `book` with `category_id` and `category` with `previous_inserted_book_id`. If database doesn't exist than this kind of schema cannot be created without `ALTER TABLE` command.
So there are two ways of creating `FOREIGN KEY` support in `sqlite_orm`:
1) easy (for lib contributors). Tables order in `make_storage` matters - if it is incorrect `std::runtime_error` will be thrown. Cross-references are not supported at all.
2) hard. Order doesn't matter at all. Cross-references are fully supported. `sync_schema` creates a dependency graph before creating table (if any of them do not exist) and creates table without references and then alters them with foreign key tables.

What do you think? Which way do you expect as a lib user? I think I'm gonna write first way firstly and test it. Later I'll improve it to the second.

**Comment by clouddra** [comment]
my use case would be closer to 1. I am mainly using the indexes as to optimize a readonly sqlite db.

**Comment by fnc12** [comment]
@clouddra thanks. I'm starting to work on foreign keys

**Comment by fnc12** [comment]
@clouddra please check cda7f36a9ab0dae93185d1222c313a9687b0b245 . I've added foreign key support. It is raw right now - it doesn't support two-columned keys and reverse foreign keys (when table A has fk to table B and reverse). And tables must be defined in `make_storage` in order of foreign keys usage - first is a parent table, next is a child table. You can see an example [here](https://github.com/fnc12/sqlite_orm/blob/master/examples/foreign_key.cpp).
Limitations described below will be erased in a future commits. Sorry for late response - I was busy with `JOIN`.

**Comment by fnc12** [comment]
Order importance is eliminated in 927a6368c600555fe4c054a9630bcf589a412cee

**Comment by fnc12** [comment]
Please check out indexes support in a0bb1e83131a06a2c44c75e048ed6d589493b80f.
