### ISSUE TITLE
build error: initializer list would use explicit constructor on Linux GCC5.4

### ISSUE THREAD

**Issue by nmgwddj** [fnc12/sqlite_orm#1013]
Build environment:
System: Linux x86_64
Compiler: GCC5
C++ STD: 14

error message:

```cpp
include/sqlite_orm/sqlite_orm.h:6835:45: error: converting to 'std::tuple<const char*, int>' from initializer list would use explicit constructor 'constexpr std::tuple<_T1, _T2>::tuple(_U1&&, _U2&&) [with _U1 = const char*; _U2 = int; <template-parameter-2-3> = void; _T1 = const char*; _T2 = int]'
             return {s.c_str(), int(s.size())};
```

**Comment by fnc12** [comment]
are you sure that GCC5 supports C++14?

**Comment by nmgwddj** [comment]
https://en.cppreference.com/w/cpp/compiler_support/14

**Comment by nmgwddj** [comment]
I found this answer, not sure if it's related: https://stackoverflow.com/questions/47534938/explicit-constructors-and-nested-initializer-lists

**Comment by fnc12** [comment]
can you test with a different GCC version?

**Comment by nmgwddj** [comment]
> can you test with a different GCC version?

Compiled successfully with gcc7 under Linux. But we may have to adapt to gcc5. I don't know if you have any suggestions for this. I can try to modify it locally for testing.

```
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Debug
compiler=gcc
compiler.cppstd=14
compiler.libcxx=libstdc++11
compiler.version=7
os=Linux
os_build=Linux
[options]
[build_requires]
[env]
```

**Comment by fnc12** [comment]
I use clang, other community guys use VC++. So yes we don't have any suggestions

**Comment by trueqbit** [comment]
sqlite_orm 1.7.1 is using a C++17 library feature here - [Improving std::pair and std::tuple [N4387]](https://en.cppreference.com/w/cpp/compiler_support/17#C.2B.2B17_library_features).
The current [dev branch](https://github.com/fnc12/sqlite_orm/blob/451a81b774123d07f45413db4f4604aae0773fb1/dev/statement_binder.h#L135) is using a std::pair instead of std::tuple, which doesn't exhibit this problem, see also a test project on [godbolt](https://gcc.godbolt.org/#g:!((g:!((g:!((h:codeEditor,i:(filename:'1',fontScale:14,fontUsePx:'0',j:1,lang:c%2B%2B,selection:(endColumn:1,endLineNumber:15,positionColumn:1,positionLineNumber:15,selectionStartColumn:1,selectionStartLineNumber:15,startColumn:1,startLineNumber:15),source:'%23include+%3Ctuple%3E%0A%23include+%3Cutility%3E%0A%23include+%3Cstring.h%3E%0A%0Astd::pair%3Cconst+char*,+int%3E+string_data1(const+char*+s)+%7B%0A++++return+%7Bs,+int(::strlen(s))%7D%3B%0A%7D%0Astd::tuple%3Cconst+char*,+int%3E+string_data2(const+char*+s)+%7B%0A++++return+%7Bs,+int(::strlen(s))%7D%3B%0A%7D%0A%0Aint+main()+%7B%0A++++string_data1(%22abc%22)%3B%0A++++string_data2(%22abc%22)%3B%0A%0A++++return+0%3B%0A%7D%0A'),l:'5',n:'0',o:'C%2B%2B+source+%231',t:'0')),k:33.333333333333336,l:'4',n:'0',o:'',s:0,t:'0'),(g:!((h:compiler,i:(compiler:g550,filters:(b:'0',binary:'1',commentOnly:'0',demangle:'0',directives:'0',execute:'1',intel:'0',libraryCode:'0',trim:'1'),flagsViewOpen:'1',fontScale:14,fontUsePx:'0',j:1,lang:c%2B%2B,libs:!(),options:'-std%3Dc%2B%2B14',selection:(endColumn:1,endLineNumber:1,positionColumn:1,positionLineNumber:1,selectionStartColumn:1,selectionStartLineNumber:1,startColumn:1,startLineNumber:1),source:1,tree:'1'),l:'5',n:'0',o:'x86-64+gcc+5.5+(C%2B%2B,+Editor+%231,+Compiler+%231)',t:'0')),k:33.333333333333336,l:'4',n:'0',o:'',s:0,t:'0'),(g:!((h:output,i:(compilerName:'x86-64+gcc+5.4',editorid:1,fontScale:14,fontUsePx:'0',j:1,wrap:'1'),l:'5',n:'0',o:'Output+of+x86-64+gcc+5.5+(Compiler+%231)',t:'0')),k:33.33333333333333,l:'4',n:'0',o:'',s:0,t:'0')),l:'2',n:'0',o:'',t:'0')),version:4).

**Comment by nmgwddj** [comment]
> sqlite_orm 1.7.1 is using a C++17 library feature here - see compiler support matrix entry on [Improving std::pair and std::tuple [N4387]](https://en.cppreference.com/w/cpp/compiler_support/17#C.2B.2B17_library_features). The current [dev branch](https://github.com/fnc12/sqlite_orm/blob/451a81b774123d07f45413db4f4604aae0773fb1/dev/statement_binder.h#L135) is using a std::pair instead of std::tuple, which doesn't exhibit this problem, see also a test project on [godbolt](https://gcc.godbolt.org/#g:!((g:!((g:!((h:codeEditor,i:(filename:'1',fontScale:14,fontUsePx:'0',j:1,lang:c%2B%2B,selection:(endColumn:1,endLineNumber:15,positionColumn:1,positionLineNumber:15,selectionStartColumn:1,selectionStartLineNumber:15,startColumn:1,startLineNumber:15),source:'%23include+%3Ctuple%3E%0A%23include+%3Cutility%3E%0A%23include+%3Cstring.h%3E%0A%0Astd::pair%3Cconst+char*,+int%3E+string_data1(const+char*+s)+%7B%0A++++return+%7Bs,+int(::strlen(s))%7D%3B%0A%7D%0Astd::tuple%3Cconst+char*,+int%3E+string_data2(const+char*+s)+%7B%0A++++return+%7Bs,+int(::strlen(s))%7D%3B%0A%7D%0A%0Aint+main()+%7B%0A++++string_data1(%22abc%22)%3B%0A++++string_data2(%22abc%22)%3B%0A%0A++++return+0%3B%0A%7D%0A'),l:'5',n:'0',o:'C%2B%2B+source+%231',t:'0')),k:33.333333333333336,l:'4',n:'0',o:'',s:0,t:'0'),(g:!((h:compiler,i:(compiler:g550,filters:(b:'0',binary:'1',commentOnly:'0',demangle:'0',directives:'0',execute:'1',intel:'0',libraryCode:'0',trim:'1'),flagsViewOpen:'1',fontScale:14,fontUsePx:'0',j:1,lang:c%2B%2B,libs:!(),options:'-std%3Dc%2B%2B14',selection:(endColumn:1,endLineNumber:1,positionColumn:1,positionLineNumber:1,selectionStartColumn:1,selectionStartLineNumber:1,startColumn:1,startLineNumber:1),source:1,tree:'1'),l:'5',n:'0',o:'x86-64+gcc+5.5+(C%2B%2B,+Editor+%231,+Compiler+%231)',t:'0')),k:33.333333333333336,l:'4',n:'0',o:'',s:0,t:'0'),(g:!((h:output,i:(compilerName:'x86-64+gcc+5.4',editorid:1,fontScale:14,fontUsePx:'0',j:1,wrap:'1'),l:'5',n:'0',o:'Output+of+x86-64+gcc+5.5+(Compiler+%231)',t:'0')),k:33.33333333333333,l:'4',n:'0',o:'',s:0,t:'0')),l:'2',n:'0',o:'',t:'0')),version:4).

Thanks for your reply. I will try develop branch.

**Comment by trueqbit** [comment]
Latest dev branch is now testing gcc as well, so you have good chances things will work for you...
Can we close the ticket?

**Comment by fnc12** [comment]
let's wait for @nmgwddj response first

**Comment by nmgwddj** [comment]
This is full log under Linux GCC5.5
[log.txt](https://github.com/fnc12/sqlite_orm/files/8705660/log.txt)

**Comment by fnc12** [comment]
looks you are still getting error. Is that correct?

**Comment by nmgwddj** [comment]
Yes, but this time with a different error.

**Comment by fnc12** [comment]
which branch do you use? `dev`?

**Comment by nmgwddj** [comment]
> which branch do you use? `dev`?

Yes, in the `dev` branch.

**Comment by fnc12** [comment]
are you using single header or no?

**Comment by nmgwddj** [comment]
I just switch the code to the dev branch and execute the following two CMake commands:

```bash
cmake -Bbuild -DCMAKE_BUILD_TYPE=Debug
# build
cmake --build build --config Debug
```

**Comment by fnc12** [comment]
weird things. I did the same on my mac but with clang and it worked well. Can you check the same with clang?

**Comment by trueqbit** [comment]
The error log that you attached is very strange:

> error: ‘connection_ref’ does not name a type: connection_ref con;

The corresponding header file has been correctly included long before.
Could you try the unmerged headers from _not_single_header_include/sqlite_orm_ and find out why gcc 5 does not work?

**Comment by trueqbit** [comment]
@nmgwddj Can we close this ticket?

**Comment by nmgwddj** [comment]
We have upgraded gcc to 7 and temporarily closed this issue.
