### ISSUE TITLE
Error while using Fetch Content 

### ISSUE THREAD

**Issue by Paras-97** [fnc12/sqlite_orm#1058]
Hi,

When I am trying to use the library using Fetch Content, it is throwing me this error.

**CMakeLists.txt**
include(FetchContent)
FetchContent_Declare(sqliteOrm GIT_REPOSITORY https://github.com/fnc12/sqlite_orm 
                    GIT_TAG origin/dev)
FetchContent_MakeAvailable(sqliteorm)
target_link_libraries(${PROJECT_NAME} sqlite_orm)

**Error:**
HEAD is now at 87c0b59 Merge pull request #1043 from FireDaemon/issues/asterisk_defined_column_order
fatal: No url found for submodule path 'tests/_deps/catch2-src' in .gitmodules
CMake Error at sqliteorm-subbuild/sqliteorm-populate-prefix/tmp/sqliteorm-populate-gitclone.cmake:52 (message):
  Failed to update submodules in:
  '/home/paras/Eaglesoft/enginemanager/build/_deps/sqliteorm-src'

make[2]: *** [CMakeFiles/sqliteorm-populate.dir/build.make:92: sqliteorm-populate-prefix/src/sqliteorm-populate-stamp/sqliteorm-populate-download] Error 1
make[1]: *** [CMakeFiles/Makefile2:76: CMakeFiles/sqliteorm-populate.dir/all] Error 2
make: *** [Makefile:84: all] Error 2

What exactly am I doing wrong here?

**Comment by fnc12** [comment]
what commands do you call? What OS do you use? I need steps to repro it. Thanks

**Comment by yellows111** [comment]
```
git clone https://github.com/fnc12/sqlite_orm.git -b dev --recursive
```
Anything that uses the recursive submodules mode will break upon pulling sqlite_orm.

As I use GitHub Actions on a repository with submodules, I need to pull such submodules into the source tree to compile.

However when doing a recursive clone, it gets stuck attempting to fetch `tests/_deps/catch2-src` (as it has no URL defined) and hard-fails, breaking the build.

Fixing this for my CI required changing it to `git submodule update --init` manually and clean-up post-build (via `git submodule deinit --force --all`).

This is inconvenient for CI, yet in the example above, the CMake base module FetchContent has a function called FetchContent_Declare, which recursively clones the repository, creating a fatal error due to said `tests/_deps/catch2-src` not having a defined URL.

**Comment by yellows111** [comment]
A CMake fix would be setting the `GIT_SUBMODULES` value to `""`
```cmake
include(FetchContent)
FetchContent_Declare(sqliteORM
    GIT_REPOSITORY https://github.com/fnc12/sqlite_orm.git
    GIT_TAG origin/dev
    GIT_SUBMODULES ""
)
```

Other than that, the problem I've described above (https://github.com/fnc12/sqlite_orm/issues/1058#issuecomment-1186151013), is why this issue is happening in the first place.

**Comment by trueqbit** [comment]
Not being a CMake expert, I am only observing:
* sqlite_orm doesn't use any submodules, and there's no _.gitmodules_ file
* _tests/\_deps/catch2-src_ is in the repo, but doesn't contain any files
* _tests/\_deps_catch2-src_ doesn't get mentioned in any CMakeLists.txt file
* _dependencies/CMakeLists.txt_ `FetchContent_Declare`s a correct URL
*  `git clone https://github.com/fnc12/sqlite_orm.git -b dev --recursive` works on my side
