### ISSUE TITLE
Is it possible to change primary keys without losing data?

### ISSUE THREAD

**Issue by minorsecond** [fnc12/sqlite_orm#1092]
I moved from this is as my primary key:

```
sqlite_orm::make_column("id", &Drink::id, sqlite_orm::autoincrement(), sqlite_orm::primary_key())
```

to this:

```
sqlite_orm::make_column("timestamp", &Drink::timestamp, sqlite_orm::default_value(sqlite_orm::datetime("now", "localtime")), sqlite_orm::primary_key())
```

I changed the `id` column definition to this:

```
sqlite_orm::make_column("id", &Drink::id, sqlite_orm::default_value(-1))
```

so that the ORM has a default value. I made no other changes and the table is truncated when doing so. Can this be done while preserving data?

**Comment by fnc12** [comment]
how do you call `sync_schema`?

**Comment by fnc12** [comment]
@minorsecond also please provide code snippet to repro your case. Thanks

**Comment by minorsecond** [comment]
Sure thing. The DB is instantiated with this (I've removed unchanged columns):

sqlite_orm::make_storage(file_name,
                                    sqlite_orm::make_table(table_name,
                                                           sqlite_orm::make_column("id", &Drink::id,
                                                                                   sqlite_orm::default_value(-1)),
                                                          sqlite_orm::make_column("sort_date",
                                                                                  &Drink::sort_date,
                                                                                  sqlite_orm::default_value(
                                                                                          utilities::date_string_to_date_int(
                                                                                                  utilities::get_local_date())
                                                                                          ))));
}

`Drink` class is as so (also irrelevant properties removed):

```
class Drink {
private:
    int id;
    std::string timestamp;

    friend class Calculate;
    friend class Database;
    friend auto initStorage(const std::string &file_name);
```

`sync_schema()` is called in the main window constructor any time the program is run: `storage.sync_schema(true);`

**Comment by fnc12** [comment]
@minorsecond I did not have time to try it out. Did you solve it?

**Comment by minorsecond** [comment]
No problem. I didn't solve it but I went another route.

**Comment by fnc12** [comment]
let me leave it opened until I try to figure out what happens here and why data is lost

**Comment by fnc12** [comment]
@minorsecond BTW you can purchase `sqlite_orm_plus`. It is a modified proprietary version of `sqlite_orm` with migrations support. It costs 1k$ per year

**Comment by fnc12** [comment]
looks like the issue is related to new column `timestamp` which has both default value and primary key. I am not sure SQLite allows doing this cause if you add a new column which is primary key and if the table already has at least two rows then you'll going to have all existing rows (> 1) with the same primary key which equals to default value. I am not sure it is right. So to solve this `sqlite_orm` issue you have to solve how you want to handle migration with raw SQLite first. You can do it manually or you can purchase a special version of `sqlite_orm` which is called `sqlite_orm_plus` which has automatic migration API which can guarantee that your data will be preserved no matter how you are going to change the schema no matter how many users use your app. You can contact me if you are interested fnc12@me.com. This issue is going to be closed cause we can do nothing her within `sqlite_orm`
