### ISSUE TITLE
What's wrong with my Query

### ISSUE THREAD

**Issue by ma-mehralian** [fnc12/sqlite_orm#1115]
This is my SQL query that works properly on SQLite:

```
SELECT class_id, COUNT(*) 
   FROM vehicles
   WHERE DATETIME(vehicles.date, 'unixepoch')> DATETIME('now', '-2 day')
   GROUP BY class_id
```

My implementation in CPP is:

```
auto statement = storage_.prepare(select(columns(&Vehicle::class_id, count<Vehicle>()), from<Vehicle>(),
	where(greater_than(sqlite_orm::datetime("vehicles.date", "unixepoch"), sqlite_orm::datetime("now", "-2 day"))),
	group_by(&Vehicle::class_id)
));
printf("%s", statement.expanded_sql().c_str());
for (auto& itm : storage_.execute(statement)) {
	printf("%d, %d", std::get<0>(itm), std::get<1>(itm));
}
```

which returns the following string:

```sql
SELECT "vehicles"."class_id", COUNT(*) 
FROM "vehicles" 
WHERE (((DATETIME(NULL, NULL)) > (DATETIME(NULL, NULL)))) 
GROUP BY "vehicles"."class_id"
```

**Comment by fnc12** [comment]
looks like everything works fine. What do you expect?

**Comment by ma-mehralian** [comment]
is it OK to use column name in `datetime` like  `sqlite_orm::datetime("vehicles.date", "unixepoch")`?

**Comment by fnc12** [comment]
it depends on whether it is ok to use column name in `datetime` like `DATETIME('vehicles.date', 'unixepoch')` in raw SQLite. As far as I know it is not ok cause `'vehicles.date'` will be treated as a string not column.

To debug why results differ try to serialize the statement using `storage.dump` function:

```c++
cout << storage.dump(statement) << endl;
```

It will show real values instead of `NULL`s cause `expanded_sql` calls `sqlite_expanded_sql` which ignores bound values but `storage.dump` doesn't call any SQLite functions, it calls built-in serializer from `sqlite_orm` which is used to serialize statement before sending it to SQLite engine.

**Comment by ma-mehralian** [comment]
Yes, `DATETIME('vehicles.date', 'unixepoch')` is not valid in raw SQLite instead `DATETIME(vehicles.date, 'unixepoch')` should be used.

Event `storage.dump` shows `NULL` instead of real values!
```
SELECT "vehicles"."class_id", COUNT(*) FROM "vehicles" WHERE (((DATETIME(?, ?)) > (DATETIME(?, ?)))) GROUP BY "vehicles"."class_id"
```

How can I pass the table column as the first parameter in `datetime`?

**Comment by fnc12** [comment]
well it looks like a bug. What version of `sqlite_orm` do you use?

**Comment by ma-mehralian** [comment]
Its v1.8
`commit 4861e407eb94740e12ea7fd496945ed5702c3f4c (tag: v1.8)`

**Comment by fnc12** [comment]
please show raw SQL query you are testing with

**Comment by ma-mehralian** [comment]
It is:
```
SELECT class_id, count(*) 
   FROM vehicles
   WHERE DATETIME(vehicles.date, 'unixepoch')> DATETIME('now', '-2 day')
   GROUP BY class_id
```

**Comment by ma-mehralian** [comment]
wow, It works!!
I am pretty sure that I test it before and it didn't compile! that's my fault!

Thanks @fnc12
