### ISSUE TITLE
How are we supposed to manage a migration which could drop data?

### ISSUE THREAD

**Issue by jakemumu** [fnc12/sqlite_orm#1178]
Hey! Question about the sync_schema system this library uses. What is meant to happen when a schema change happens which would cause data to be dropped or lost in production? 

Obviously that can't be the case. Is it recommended for us to manually write some sort of function outside of sync_schema? 

I've been working with this library on a project, I'm getting fairly close to release but this issue has me concerned.

**Comment by fnc12** [comment]
@jakemumu the schema provided in `make_storage` call can be changed by developers from time to time and one cannot make a universal algorithm of `sync_schema` which always will make a perfect migration. E.g. we have a table `users` with `id` and `name` columns. The table has rows count > 0. Now we want to split name by space to two different columns instead of `name`: `first_name` and `last_name`. `sync_schema`  can't know how you are going to fill `first_name` and `last_name` for existing rows. In that case replacing a column `name` with two different columns which don't have `DEFAULT` constraints and can not contain `NULL` will drop and recreate the table cause it is the only way the schema can be synchronized automatically.

In case you need to preserve the data for all the time and you would like to make migrations logic with `sqlite_orm` you can try yo use `sqlite_orm_plus`. `sqlite_orm_plus` is an enhanced version of `sqlite_orm`. It has closed source and license can be purchased from 1000$ per year per project and higher. For more information you can visit https://sqliteorm.com/pricing. `sqlite_orm_plus` allows adding migrations logic which allows performing migrations with any custom data changes. This API allows 100% data preserving.
