### ISSUE TITLE
Error maping object - v1.8.2 & GCC 11 

### ISSUE THREAD

**Issue by jairoareyes** [fnc12/sqlite_orm#1193]
Hi friend, I'm having this error when trying to map an enum class. I did this before (sqlite_orm v1.7 & GCC 7) and it works well. How can I solve this issue? Thanks in advance. 

```
/usr/local/include/sqlite_orm/sqlite_orm.h:18540:69: error: passing ‘const sqlite_orm::row_extractor<models::ClassModel>’ as ‘this’ argument discards qualifiers [-fpermissive]
18540 |                                   res.push_back(rowExtractor.extract(stmt, 0));
           |                                                 ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~
```

**Comment by jairoareyes** [comment]
I identified the issue is in this statement:

```
.select(&model::property, where(between(value, &Entry::start, &Entry::end)), limit(1))
```

**Comment by fnc12** [comment]
show `model` and `Entry` declaration please

**Comment by jairoareyes** [comment]
Hi, I just noticed that `model` and `Entry` is the same class. The class is: 

```cpp
struct model
{
std::string id;
uint64_t start;
uint64_t end;				
::models::Property property;
}
```
Where, `models::Property` is:

```cpp
enum class Property : uint8_t
{
    value1 = 0x00,
    value2 = 0x01,
    etc...
}
```
I made the enum bindings according to [the example.](https://github.com/fnc12/sqlite_orm/blob/master/examples/enum_binding.cpp)

**Comment by trueqbit** [comment]
Hi @jairoareyes,

it would be useful if you always gave the full context right away! First, it would be much easier to investigate a problem, and second - while compiler messages are often not easy to follow - it is easier to understand what the compiler is trying to tell us (in a somewhat convoluted way).

In this case, it's that your `row_extractor<models::Property>::extract() const` method must be const-qualified.
This is because the row extractor is captured in a lambda that cannot be changed.

Anyway, thanks for pointing it out, we either need to update the examples, or - which I don't prefer - allow mutable row extractors for a while.

**Comment by jairoareyes** [comment]
I put both `models::Property extract() const` and `row_extractor<models::Property>::extract() const` as const, it works perfect. Thanks for your support.

**Comment by trueqbit** [comment]
Hi @jairoareyes, you might be interested in the latest dev branch. Otherwise it seems we can close this ticket?

**Comment by fnc12** [comment]
I am sure we can close it. If @jairoareyes or anyone else still has this issue they are free to reopen it
