### ISSUE TITLE
Alternative APIs  taking std::error_code as last argument, and no-throwing never. Like std::filesystem API.

### ISSUE THREAD

**Issue by raidenluikang** [fnc12/sqlite_orm#1194]
Are you planing  introduce alternative APIs   where never throwing exception, but  put error  to std::error_code ?

**Comment by fnc12** [comment]
I am not sure about that. Why do you need it?

**Comment by raidenluikang** [comment]
I thought that, it will be useful when build project with -fno-exceptions.  Every error situation handle by hand)

**Comment by fnc12** [comment]
`-fno-exceptions` is actually is an alternative C++, parallel language which is not good. Initially my opinion on not adding `-fno-exceptions` support is based on idea that C++ community has to have only one C++ cause otherwise all the libs including `sqlite_orm` will have to have 4 versions:
- with exceptions and without rtti
- without exceptions and without rtti
- with exceptions but without rtti
- without exceptions but with rtti

This practice is not good and leads to dividing the community and the code. The same happened with python with 2.7 and 3.4 versions and the world had (and still has) two pythons. That's why `sqlite_orm` doesn't have support for alternative C++ versions. This projects selects only one C++, the most popular: with exceptions and rtti. But you can fork `sqlite_orm` and make it on your own of course

**Comment by raidenluikang** [comment]
sqlite_orm recently abandoned  rtti ).

So there will be two versions:  with exceptions and without exceptions. What's wrong without exceptions API ? 

I'm developing in mobile native c++, and planning use -fno-exceptions in long future. Because many of think can't work with exceptions in my case, also I have a lot of 3rdparty libs also not supported exceptions.

**Comment by fnc12** [comment]
> sqlite_orm recently abandoned rtti ).

ok it means that I was wrong in my previous comment with titles of C++ versions but anyway there is only one version of `sqlite_orm` existing.

> What's wrong without exceptions API ?

Nothing wrong. It is a matter of personal preferences. Exceptions are used by most of C++ projects I met so if we have to choose between exceptions and no-exceptions better select exceptions.

**Comment by raidenluikang** [comment]
About python 2 vs python 3, problem is not, there two different community. The python 2 can't support python 3 libs, and vice-versa.
There no happened dividing community sqlite_orm, if added std::error_code.

**Comment by raidenluikang** [comment]
All existing exceptions very easy implemented over non-throwing API. Like boost/asio,  or std::filesystem.  Both of actually call non-throwing api internally,  and throws std::error_code if needed.

**Comment by fnc12** [comment]
> here two different community.

one language but two communities with two excluded sets of libs. One language is split by two. That's exactly what I am talking about

**Comment by fnc12** [comment]
> ll existing exceptions very easy implemented over non-throwing API. Like boost/asio, or std::filesystem. Both of actually call non-throwing api internally, and throws std::error_code if needed.

ok I am not arguing here. Anybody can for `sqlite_orm` and implement it

**Comment by raidenluikang** [comment]
OK, maybe in C++23, std::expected will be added ? ))

**Comment by raidenluikang** [comment]
I mean that, all modern classes trying to avoid exceptions inside library: std::optional, std::variant, std::expected, std::filesystem.

 this will give developers more choice. And avoid hot point inside library.

**Comment by fnc12** [comment]
`std::expected` is a nice feature (just like `Result` in Swift and Rust). But we need to think about it first

**Comment by fnc12** [comment]
main issue of adding alternative API is that all future features will have to support two versions of libs in one. It is easy to implement it right now but it will increase the volume of supporting work twice. That's why I don't think it is a good idea. But as I said before: if you want you can fork the lib at any moment and implement it on your own especially if it is so easy

**Comment by raidenluikang** [comment]
>> if you want you can fork the lib at any moment and implement it on your own especially if it is so easy
Thanks, I'll think about it.

**Comment by fnc12** [comment]
@raidenluikang if you don't have further question I'd ask to close this issue cause no work is going to be performed here
