### ISSUE TITLE
Exception in sync_schema on Clang

### ISSUE THREAD

**Issue by ivanKushnarenko** [fnc12/sqlite_orm#1196]
I tried sqlite_orm with Clang compiler and during call of sync_schema Exception occured 
```
terminate called after throwing an instance of 'std::system_error'
what():  unrecognized token: ""L▬rРЎ": SQL logic error
```

Here's my code:
``` C++
struct User
{
    int id;
    std::string name;
};

using namespace sqlite_orm;

auto storage = make_storage("db.sqlite",
                            make_table("users",
                                       make_column("id", &User::id, primary_key().autoincrement()),
                                       make_column("first_name", &User::name)));

auto sync_res = storage.sync_schema();
```

During debugging i found out that name of the column User::name in storage differs from the one I gave:
![image](https://github.com/fnc12/sqlite_orm/assets/47792393/ed065728-2a54-4e85-9b4a-134c8c088321)

Also u should know, that i use clang compiler with binaries compiled for mingw (installed with MSYS2 for Windows)
I caugth this exception both on master and dev branch

With G++ from Mingw compiler everything works fine

**Comment by trueqbit** [comment]
Uh oh, this looks like either undefined behavior or a compiler error. Since we test in many environments, I suspect the latter.

Does it occur in a simple test program or as part of on of your applications?

I know this is tedious, but, to help us, could you please:
- Determine the exact versions of your environment: MSYS2 package, mingw, clang and the libcxx standard library.
- Debug the `make_column()`/`make_table()`/`make_storage()` calls and find out where the column "first_name" is lost?

**Comment by ivanKushnarenko** [comment]
It was simple test program, I have attached all code that matters in the whole project in my previous comment.

MSYS_NT-10.0-22621 version 3.4.6.x86_64 
gcc version 11.3.0
clang version 15.0.7

Problem seems to be in move-contructor of std::string. After call of ` make_column("first_name", &User::name)` returned column contains wrong column_identifier, but string argument `name` passed in make_column funciton is correct. As I see string move-constructor correctly copies all buffers but something goes wrong when column_name is put in column_t instance. Unfortunately I was not able to debug deeper that this std::string move constuctor called from column_t constructor

**Comment by trueqbit** [comment]
Yep, that's a compiler bug with clang/mingw, see example on [godbolt](https://godbolt.org/#z:OYLghAFBqd5QCxAYwPYBMCmBRdBLAF1QCcAaPECAMzwBtMA7AQwFtMQByARg9KtQYEAysib0QXACx8BBAKoBnTAAUAHpwAMvAFYTStJg1DIApACYAQuYukl9ZATwDKjdAGFUtAK4sGEjaSuADJ4DJgAcj4ARpjEIACcABykAA6oCoRODB7evv6p6ZkCIWGRLDFxSbaY9o4CQgRMxAQ5Pn5cAXaYDlkNTQQlEdGxCckKjc2teR22EwOhQ%2BUjSQCUtqhexMjsHOYAzKHI3lgA1CZ7buPEocDn2CYaAIL7h8eYZxcEXin0dw/PZgODCOXlO5zcXkctEIAE8/k8XsC3h83E4rphWPDngjAVgaGETgB9IQAFQASgBJcIAcQpAC1sAANCCqFZnQGqf77PELImkyk0%2BnYFls4nkqm0hnM1lcnEHKh4omEhBMBSE5ApFKEpgEAjXKKQzBc3GYfHvIQARSCFJJ2EJAHkyQBZQkACUeQkJbmUykJjxJ4oscltEB1etFytV6s12t1%2BsNobjK2NexqShTPIJluttodzrdHq9Pr9AcpQZDYeIbI0QRTrjwVFlAPlSo1WqYwGAxEwwB1mEJUVVmAUH3uewAIiczBouAA2DR7WtyzPmq02u2Ol2PanUsnYan%2Bu0WD3YT1COQ%2Bx228d1hj4RsIuUNk7Z9d5l3uz3e33%2BwPB4UMKghJeAweAAI5eP2TDoOg3YKAobJ/BOU4zokC5Ls2K4vmuuaboS4T2nI4QUhacjYI847jnuQhCGcACsVgMYBwGgRBUEwXBCgmHRN48XWtDpsupq8q%2BuH5gRREkWRFFUaeQi3veTbcsJWY4Ru%2BZuEEjw0sSF7KNRnpOhSNESoSFhko8binhAAB0dlsqJ6kupp2nUrpPoGRA5hmAAtAA6iweDwTcPlRMQTDbFxZhmKQSoAGqPH6ZLUp6hLJo%2B2KPMwbAKCkEXvKEBCxMwtBnAA7FYTxXF4DgnGguQMISeBYIIDZ4LE5WVZlJw9ScAD0ABUA3/L1o0nANPVTAwJzZZgNkjWNPUDX1C09eM6AgCAVw3DNrBGnsXUmGVN4HU21W1ZgLApAQMKEkouodUdVjHech1PINq3jT12DAkwKQKF4BhFSOqBRNo3QECcbBLMQJxpIVsQjgQKqQ007xeEo6AnKqdWeG0Jw0DU6AKKQn0Tdjd4nAA7gg6TvKD4O1UFUN/SkmBY0QJzjCQHZzWTPX8yc1InMzTBQ5dFQnAzENw6gCOwyQ4swwTIE9AIsvy4LtGi0rktUKrdTTfDggdYrJjzpd123fdRXEObGhkytTxFVdQP7W4RyqiO1KxZ78Evli52Q/VbSEoTtBY09n0Yzt0MVISxu24SkPnJO1KvdHGRGFzmAPcQycwmzHyTvJp0ZaNg3DU8i1LT1ToSx1icdRj7MnJz3bQdjBPtRHJwAG5iJB83VzX5MUlQIuQzr0u1XHjdyybsOECLI5iAoqAnC3HMb1T1xFV34dYwP3h8yPi3LZ9aAMOMuuxAnC9J5Dc/503dtl91vWV59o3k0Iue27fWG%2BtgSGzbjvPe7wxaH37oPI0Z8xoX3gY5d8%2BFCLEVIuRSiBlL4CBvjbO%2BN0i74LfodF679/gfXgeTH6oh/qAz7KvNu3x6BSwniHXwuNr56iYIVBQw9Hg/wFlQnq9oUh2RsivLuV8rg8MECOPKyAADWsU5rAAkSka4LAmi3UUZgW6BBYogXApBZOJxc6mCoU7R4Lsfh9nBH7PhdkTiiMDnqGqwc8a%2BHVLg7hvDOqZx2tI3xciC5F1TlzAgG0QBfB%2BO7UR4ikJvQEb1ZBeEJLoOklguSOCuHhV4aE94QS8lyIzgiMhSSv7CJOFNE4mYigMH4YIs4VSKRT0YWgK6hRQGoAniQZGqBgACDECLBg/BiBaNAdzbsWNQi1IbFQWIjBIaDiUHVAw8FhyNN6og6xls3b2PWd7X2hyXzHK9uI5xKRXHEHcbjBqpiQB3NDs1JZbVYi%2B08Y1Q%2B4IfYBz2NgD59yimyIIFxC48S7J3H8U%2BKgd5TTYRzE5P0O49wHlzMeIQp53LKCvNgG88D2GNQIBAdam1trZ1mrFYWz9lAP3eS%2BHOedYqkuicwuJYjIX/KlikNkIBv69UJU1FqjhCZ2wqiylgqA%2B6YAgLNZMx1AWh2%2BRcX5pd7gVRpXSsgjLbZHXHKTeBo1BXAt4eCCF81/lPQlVKmVqAeV6v8S9OU9YHzPHKVyJ1mUbH7IuA4k4ToznwQuS4y1Tx5YlU2oKgg4IA0jNthGkAlsbp3X/vS81UKtG6O8Q1ElkSyV6h2pS/1UNYrms4TI3hiEKqfT6n1BFb48IuR0ueDyclCRGRMjpcyllrLdi%2BMQaaVq80gEldK2Ve01glsdfqiJUTM39hifQCAJq5HiPleOZM78K51p8rOza87k5sogGydAqBhwMDABwSGVMSCKJGZw7QBssjU0IAgOZ3ZaorIKqBRwYg8AAC8dTPsMFjVJ4k0FSUwbJGiBNFaGDMVdG6TDYmfT7ZsQd4rh2jplXK2KLBYpRwVXukdTAs2LplSu0Fa69WlOST1WtJxd03uIIori8CGNoYHZ1a1Y7cNTsIzOp6lHHHzReu6sp%2BLMr/CDicRQj1q3wJAhkYAYQsa0AEMAE46ns7NVo6NFl5LNM0GIOMQks1aM0fIVVNxtVKPTos2GwQLNQjHuhXR4jaBIQonBOyMwCA8DeW8xcYjrhaB6d6kwSEG9kBcGLizLNhKvLRV09FAjZhZxybiCAZqHzckgoE5urqo1Iuc2QGYOLB7EveWM6Z8zqX2QZaUFlmrBAzMTvC2tYdnmU4XB8zFmys0bIZH/TKxCvXgsstCx1jzGwetuD61wAbe0gtuBC3eMLW7eosu6ytuqZgltsCGwB0bu3Jvrem9t2bu2ysHfeOCHzZ30AbaK71Tj00HbkM9RwNYtBOB0V4H4DgWhSCoE4PNyw1guYbC2HdwEPBSAEE0N9tYiiQB0Q0DZSQdFJCzkSGYeIew6J0S4HsPYMVfscEkADpHIPOC8AUCAAIiOgffdIHAWASBMCqG6FFsgFBQzEGAAoZQhgahCFplTQH8OOkpDoEBgQIuwi0HF6gSXNOZd0BGIFIwVNZySGAsgZo6oDBGEJHODQMUNf0GIOEPadPSBW9iPaSEKu1cs8CNz5AjxBcM44LwLn3QGj4EB7wfgggRBiHYFIGQgg5NqBp7oLg%2BhDDGGsNYfQeAogM8gGsO1htfc%2BXWqnUwEPLDTl4Da4g1wsDZ%2BPesTY2w9DrVCIrsXEupe8F3n9TgPAft/ep%2B70HHBsCe95/60I1I/JrJTycOcNkMflYgODqwlhYq4EIGbOHKxeDM60CsFHIBJDxBstjuiewuBlQ0HryQiRZyzjKvoTgVPSCA%2BB0P%2BnjOEdI/34/jgZgB9v72677I6kDSomZZCH5AA%3D). The problem is that clang/mingw has trouble to construct an empty `[[no_unique_address]] column_constraints::constraints` tuple member from a temporary tuple (created by `std::make_tuple()`). It works if this constraints tuple is also directly braze-initialized (which is better coding anyway).

If you are so inclined, could you report the clang bug?

**Comment by trueqbit** [comment]
@ivanKushnarenko The latest "dev" branch should fix your problem.

**Comment by ivanKushnarenko** [comment]
@trueqbit Thanks a lot for your fast response. Everything works!
