### ISSUE TITLE
sqlite-orm fails to compile under uwp

### ISSUE THREAD

**Issue by jimwang118** [fnc12/sqlite_orm#1252]
When I failed to compile sqlite-orm under uwp, the error message is as follows.

```
MSVCRTD.lib(exe_main.obj) : error LNK2019: unresolved external symbol main referenced in function "int __cdecl invoke_main(void)" (?invoke_main@@YAHXZ)
tests\unit_tests.exe : fatal error LNK1120: 1 unresolved externals
ninja: build stopped: subcommand failed.
```
I have enabled the `test` feature. This feature generates the `unit_tests.exe `executable program, but under uwp there is an error message indicating that there is no corresponding executable main function entry? Is this a normal design or is it a problem?

**Comment by trueqbit** [comment]
We are using Catch2 for unit testing.
Do you know whether it is supported on UWP, or whether it needs special handling?

_tests\CMakeLists.txt_ [links](https://github.com/fnc12/sqlite_orm/blob/ff7c878af872f7987b62d825284fb25d6043af10/tests/CMakeLists.txt#L172) against `Catch2::Catch2WithMain`:
```
target_link_libraries(unit_tests PRIVATE sqlite_orm Catch2::Catch2WithMain)
```

**Comment by fnc12** [comment]
@jimwang118 does it work now?

**Comment by jimwang118** [comment]
> @jimwang118 does it work now?

Still the compilation failed.

**Comment by trueqbit** [comment]
vcpkg's “x64-uwp” triplet sets the CMake variable `CMAKE_SYSTEM_NAME=WindowsStore`, which instructs CMake to add the `/D_UNICODE` and `/DUNICODE` compiler flags. Catch2 v3 will then provide a [definition of `wmain()`](https://github.com/catchorg/Catch2/blob/4e8d92bf02f7d1c8006a0e7a5ecabd8e62d98502/src/catch2/internal/catch_main.cpp#L26) instead of `main()`.

For some reason, the msvc linker will not take `wmain()` from a static library.

PR #1295 explicitly sets the entry point of the unit test executable file.

**Comment by trueqbit** [comment]
@jimwang118 I have tested the “x64-uwp” triplet, but it would be good if you could check that too.
