### ISSUE TITLE
upsert support and affected rows support

### ISSUE THREAD

**Issue by neevek** [fnc12/sqlite_orm#242]
This is a feature request list:

1. I think this is quite a common requirement, as in MySQL there's `ON DUPLICATE UPDATE`, in sqlite, there's a newly added `UPSERT` statement: [https://www.sqlite.org/lang_UPSERT.html](https://www.sqlite.org/lang_UPSERT.html).

2. Support for returning affected rows of `insert` and `update` method calls.

**Comment by fnc12** [comment]
use `storage.replace`

**Comment by fnc12** [comment]
Ok. It is very interesting feature. Could you please write exact SQL query you want to reproduce. It would help me very much. Thanks

**Comment by neevek** [comment]
It's like examples in the [https://www.sqlite.org/lang_UPSERT.html](link) I pasted:

```sql
CREATE TABLE vocabulary(word TEXT PRIMARY KEY, count INT DEFAULT 1);
INSERT INTO vocabulary(word) VALUES('jovial')
  ON CONFLICT(word) DO UPDATE SET count=count+1;
```

**Comment by fnc12** [comment]
Ok thanks. I need to think about it. I'm sure it is available to implement this feature in `sqlite_orm`

**Comment by fnc12** [comment]
Added into [TODO](https://github.com/fnc12/sqlite_orm/blob/dev/TODO.md) in dev branch. Thanks

**Comment by fnc12** [comment]
@neevek Hi. Thanks for your patience. Right now I am finally working on this issue. Could you please provide more examples for it to make sure I do everything right.

**Comment by alexprogrammr** [comment]
@fnc12 Hi! Thank you a lot for this awesome library!

I'm also very interested in `INSERT ON CONFLICT UPDATE` functionality. What can I do from my side to make this feature available as soon as possible? I see that you wrote that you are currently working on that. Do you still need more examples for it?

**Comment by fnc12** [comment]
@alexprogrammr more examples would be great

**Comment by alexprogrammr** [comment]
Raw SQL query could look like this:
```
CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY, firstname TEXT, lastname TEXT);

INSERT INTO users(id, firstname, lastname) VALUES(0, "foo", "bar")
    ON CONFLICT(id) DO UPDATE SET firstname=excluded.firstname, lastname=excluded.lastname;
INSERT INTO users(id, firstname, lastname) VALUES(0, "john", "smith")
    ON CONFLICT(id) DO UPDATE SET firstname=excluded.firstname, lastname=excluded.lastname;
```

The second call to `INSERT` will simply update listed fields without raising a `constraint failed` error.

**Comment by fnc12** [comment]
@alexprogrammr thank you. I am not working on this issue right now. Right now I am working on this issue https://github.com/fnc12/sqlite_orm/issues/561. You can inspect which issue I work on using `in progress` label. Also you can make it by yourself with a PR into `dev` branch

**Comment by alexprogrammr** [comment]
@fnc12 if you don't mind, I will add this functionality in the nearest future.

**Comment by fnc12** [comment]
@alexprogrammr I have a proposal for your query

```sql
CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY, firstname TEXT, lastname TEXT);

INSERT INTO users(id, firstname, lastname) VALUES(0, "foo", "bar")
    ON CONFLICT(id) DO UPDATE SET firstname=excluded.firstname, lastname=excluded.lastname;
INSERT INTO users(id, firstname, lastname) VALUES(0, "john", "smith")
    ON CONFLICT(id) DO UPDATE SET firstname=excluded.firstname, lastname=excluded.lastname;
```

```c++
storage.insert_into<User>(columns(&User::id, &User::firstName, &User::lastName), 
	values(0, "foo", "bar"), 
	on_conflict(&User::id).do_(update(set(c(&User::firstName) = excluded(&User::firstName),
		c(&User::lastName) = excluded(&User::lastName)))));
```
First of all I think we need to add `storage_t::insert_into` API which can be called 'raw insert' just like `storage_t::select` is called 'raw select'.

Then we need to add `on_conflict` public function.

**Comment by xingbiyanshu** [comment]
@fnc12 
this realization:
storage.insert_into<User>(columns(&User::id, &User::firstName, &User::lastName), 
	values(0, "foo", "bar"), 
	on_conflict(&User::id).do_(update(set(c(&User::firstName) = excluded(&User::firstName),
		c(&User::lastName) = excluded(&User::lastName)))));

It is too complex, can it be realized in the following form:
storage.insert(user_obj, 
	on_conflict(&User::id)
	.update(&User::firstName, &User::lastName)
);
these are all the infos users need to provide, and this API will be much more comfortable to use.

**Comment by fnc12** [comment]
@xingbiyanshu thanks for the suggestion but your version lacks options for specifying some things. E.g. `default_values` instead of `columns` and your version of `update` which looks like this `update(&User::firstName, &User::lastName)` doesn't allow inserting statements as assignment operator operands in case if I want to let's say increment excluded value to avoid conflicts. Your suggestions looks more like a very specified option of existing raw `insert` API so you can make your own function (free func or member func in storage subclass) which accepts only parameters you need and calls raw `insert` API which is too long from your opinion

**Comment by xingbiyanshu** [comment]
@fnc12 Thanks for your response.
Yes, you are absolutely right. However, this interface is still too complex, perhaps it's designed this way to accommodate every possible scenario.

Nevertheless, there are many common and straightforward use cases where providing a more user-friendly version of the interface would be highly beneficial.

For example, a user might simply want to achieve an "insert if not exists, otherwise fully update" requirement. Intuitively, in its minimal form, the user should only need to provide the record object, calling the upsert interface like this (hypothetical, as it's not implemented in sqlite_orm): "upsert(user);". This would imply using the primary key column(s) as the on_conflict arguments and all other columns as the arguments for the update. This is entirely feasible as long as we know what the primary key of the 'User' struct is.

This is particularly useful for large structs with dozens of fields that need to be listed—not just once, but repeatedly—especially when the goal is to perform a "full" update. The current approach is quite cumbersome.

Another common scenario involves updating only specific columns. Ideally, it could be used like this: "upsert(user, {&User::firstName, &User::lastName});". This would mean using the primary key column(s) as the on_conflict arguments and the specified columns as the update targets.

In summary, from a user's perspective, this interface is overly complex in many scenarios, likely because its high level of generality necessitates covering all cases. Nevertheless, I believe it is essential to encapsulate a more user-friendly 'upsert' function.

In my own project, I have wrapped an 'upsert' functionality based on sqlite_orm. For the two scenarios discussed above, it can be used as follows:
`

    User user{1, "Mao", "Zedong", 1893, 3 };

    orm.save(user);

    user.lastName = "Anying";

    orm.upsert(user); // onconflict(&User::id).doupdate(all other columns)

    orm.upsert<Columns<&User::id>/*onconflict*/, Columns<&User::firstName, &User::lastName>/*doupdate*/>(user);

`

However, I haven't delved deeply into the design philosophy of sqlite_orm or the abstraction layer it operates at. It's possible that a wrapper like mine may not be suitable for implementation directly within sqlite_orm itself, and might instead be better left for users to implement according to their own needs.

**Comment by fnc12** [comment]
> Yes, you are absolutely right. However, this interface is still too complex, perhaps it's designed this way to accommodate every possible scenario.

Yep exactly it is designed to accommodate every possible scenario.

> Nevertheless, there are many common and straightforward use cases where providing a more user-friendly version of the interface would be highly beneficial.

I understand your concern but it still looks for me like creating a very specialized lego item which is usable only in very rare cases but of cause which makes people who uses it really happy then ever.

> orm.upsert(user); // onconflict(&User::id).doupdate(all other columns)

Looks pretty good actually. I'd like to have it in `sqlite_orm`. Let me disclose design ideas of `sqlite_orm`: we try to cover all SQL statements existing in SQLite with C++ DSL and make it type safe to reduce amount of errors and provide intellisense right in user's IDE due to DSL. So when users asked for UPSERT first we checked [UPSERT doc on SQLite website](https://sqlite.org/lang_upsert.html). Docs say there is no `UPSERT` keyword in SQLite at all, it is more about `ON CONFLICT` clause which has to be implemented. So it means if we make `upsert` API in `storage_t` class what user will expect especially if (s)he knows SQLite well enough and knows that `UPSERT` keyword is missing in SQLite? Yeah I know you might say that we have `remove` func which calls `DELETE` and it probably better be named `delete` as well but `delete` is a reserved word so it is either `delete_` or something else. It is a tradeoff.

On the other hand your suggestion about simple `storage.upsert(user)` which expands in `onconflict(&User::id).doupdate(all other columns)` looks like a really good idea for a custom CRUD API. What I mean: `storage` has CRUD and non-CRUD APIs. CRUD is PK based APIs which usually built around object in C++ representing a row in SQLite table. And CRUD funcs like 
- `get`
- `get_no_throw`
- `update`
- `remove`
- `replace`
- `replace_range`

actually are created as simplified APIs for exactly cases like yours. So I think this suggestion can be implemented but also let's ask @trueqbit 's opinion. I am feeling ok with creating such API even though `UPSERT` keyword is going to appear in SQLite. [Keywords list BTW](https://sqlite.org/lang_keywords.html). 

> orm.upsert<Columns<&User::id>/*onconflict*/, Columns<&User::firstName, &User::lastName>/*doupdate*/>(user);

This doesn't seem to compile cause `&User::id` is not a type, it is a value and it is not a constexpr valueso it cannot be put in template brackets We can call something like `Columns<decltype(&User::id)>` but in that cause we loose runtime offset value of `&User::id` member pointer. Probably you are talking about

```c++
orm.upsert(user, &User::id, columns(&User::firstName, &User::lastName));
```
which looks more like a compilable code. If I get you right I am not sure about implementing this in the lib cause it is lesser popular case than simple `orm.upsert(user);` but also let's hear @trueqbit as well. Probably he will suggest something more beautiful.

Anyway even though we never implement what you expect from us we can make a tradeoff like this: we will implement what you want inside a dedicated example so you just copy and paste it in your code just like we did with `any.cpp` example and many other [examples](https://github.com/fnc12/sqlite_orm/tree/master/examples)
