### ISSUE TITLE
Add fluent API for query

### ISSUE THREAD

**Issue by soroshsabz** [fnc12/sqlite_orm#251]
ITNOA

I think [fluent API](https://en.wikipedia.org/wiki/Fluent_interface) is good choice for query like [sqlpp11](https://github.com/rbock/sqlpp11). it is more readable than classic function input arguments.

thanks very much for great library :)

**Comment by fnc12** [comment]
Fluent interface exists in some places where it fits the most. E.g. `foreign_key` function https://github.com/fnc12/sqlite_orm/blob/master/examples/foreign_key.cpp

**Comment by fnc12** [comment]
Is the issue actual?

**Comment by soroshsabz** [comment]
@fnc12 I think it is very good to have fluent API for query, it is very convenient for developers like [LINQ fluent API in C#](https://stackoverflow.com/a/823155/1539100)

**Comment by soroshsabz** [comment]
@fnc12 I think it is actual and good enhancement for this library

**Comment by fnc12** [comment]
Fluent API is implemented in some places but not everywhere. Where exactly do you miss fluent API in `sqlite_orm`?

**Comment by fnc12** [comment]
Not required

**Comment by soroshsabz** [comment]
I think say exactly that good to add API something like below

```C++
var query = fullNames
  .SelectMany (fName => fName.Split().Select (name => new { name, fName } ))
  .OrderBy (x => x.fName)
  .ThenBy  (x => x.name)
  .Select  (x => x.name + " came from " + x.fName);
```

**Comment by fnc12** [comment]
It cannot be adapted this way to templated API. Also why don't you like current API? Current API mostly repeats SQL API and that means current API very clear. Also fluent API exists in some local places:
`foreign_key(&Track::trackArtist).references(&Artist::artistId)` or `order_by(&User::name).collate_rtrim().asc()`. Why local and not global? Cause it generates less template instantiations. So the difference between current API and fluent API is that you need to place comma instead of dot: `storage.update_all(set(assign(&Track::trackArtist, 3)), where(is_equal(&Track::trackName, "Mr. Bojangles")));`. This is why it is "Not required"
