### ISSUE TITLE
Project license

### ISSUE THREAD

**Issue by ibakirov** [fnc12/sqlite_orm#3]
Under which license does this project?

**Comment by fnc12** [comment]
I need help here: tell me please what is the best suitable license with no boundaries. I mean license that allows using of this code inside any project even in proprietary. Thanks

**Comment by ibakirov** [comment]
Look at BSD, MIT or Apache Software License

**Comment by fnc12** [comment]
please check out 06d8fafadb62a51d23503ff304255d99b369b5b7 commmit

**Comment by me21** [comment]
Now that the project is distributed under AGPL license freely and under MIT license after $50 fee, do I get access to project updates after paying that fee? Or do I get only the version I paid for?

**Comment by fnc12** [comment]
@me21 you get access to the project updates after paying that fee of course. Please feel free to update

**Comment by gitmodimo** [comment]
Website states 50$ per year per project. Can you clarify/confirm?
From what I understamd, the purchuase of the license allow to use this library with all updates for one year after purchuase.
My quesrion is can I use the library after one year up to last version that was available at the time in perpetuity?

**Comment by fnc12** [comment]
@gitmodimo if one year is passed and you did not pay for one year more it is prohibited to use the lib in closed source project, only open source

**Comment by vlgmod** [comment]
@fnc12 I’m asking here because it might be of interest to others. I haven’t found any document that explains the usage restrictions for closed-source projects.

I would like to use sqlite_orm in a closed-source library, and the MIT license seems suitable. However, I need more details to determine how many licenses I need to purchase and to confirm that I can use sqlite_orm under these conditions.

  * If I stop paying, can I still use sqlite_orm and build my project after one year, as long as I don’t update sqlite_orm’s source code?
  * If I stop paying, can I still use and sell my project after one year, provided I don’t build sqlite_orm or my project again?
  * I want to build a dynamic library (DLL/SO) that uses sqlite_orm. This library will be distributed to customers, so they can create their own closed-source GUI or CLI software. This library will also be used by a closed-source application (which doesn’t directly use sqlite_orm). Do I need one license (for the library), two licenses (for the library and the application), or 2+n licenses (2 + one for each customer’s project)?

**Comment by fnc12** [comment]
@vlgmod 

> If I stop paying, can I still use sqlite_orm and build my project after one year, as long as I don’t update sqlite_orm’s source code?

No you can't use if you stop renewing cause it is a subscription model. No matter you update `sqlite_orm` with the origin or no

> If I stop paying, can I still use and sell my project after one year, provided I don’t build sqlite_orm or my project again?

Actually not cause the usage of `sqlite_orm` is illegal. I mean you can do it technically but it will be illegal cause it will break the license.

> I want to build a dynamic library (DLL/SO) that uses sqlite_orm. This library will be distributed to customers, so they can create their own closed-source GUI or CLI software. This library will also be used by a closed-source application (which doesn’t directly use sqlite_orm). Do I need one license (for the library), two licenses (for the library and the application), or 2+n licenses (2 + one for each customer’s project)?

The license for closed source projects is purchased per target. Target is a final product you sell. If you sell an app e.g. for iOS and Android then it requires two licenses even though you have the same code compiled for different platforms. If you have two apps for both platforms just like Uber has (for drivers and for passengers) it means 4 licenses. No matter how many times you update apps, it requires licenses amount equal to amount of targets. Target is usually a product in Xcode/Visual Studio/CMake/Bazel terms. In your case if you just produce a dynamic lib and sell it to your end customers it means you have one product so one license is required for you. 

Of course a question may arise about targets and products logic like your customers reuse `sqlite_orm` purchased once for unlimited amount of targets. It is a very interesting case which we've never faced before. Let's describe it in private email. Please send me an email to fnc12@me.com. Thanks
