### ISSUE TITLE
Add a possibility to create classes from a schema

### ISSUE THREAD

**Issue by linux-fan-dave** [fnc12/sqlite_orm#396]
It would be good to generate classes and the required make_storage code from a given sql schema.

**Comment by fnc12** [comment]
ok. But how would you specify "create public members" or "create private members with getters/setter"? And how would you specify type of getters and setters?

**Comment by linux-fan-dave** [comment]
I was thinking about a template engine -> something like [mustache](https://github.com/no1msd/mstch). This way the converter creates a data structure with all the tables and all the properties. The template renders this data structure to c++ code. Some sample templates could be provided to create c++ classes or std data structures which contain the code. The user could extend this easily by changing the template.

**Comment by linux-fan-dave** [comment]
I implemented a [sketch](https://github.com/linux-fan-dave/sqlite_orm/commit/22623c3d3e7887f9b0530bfa864a64fbde58b7f9) of the idea. Is there any chance to have code like this being added at all? Does this make any sense?

**Comment by linux-fan-dave** [comment]
A different approach would be to have database schema exporter tool. It could reside in a different git repo and just provide a template for sqlite_orm. However I would prefer to ship it inside of sqlite_orm. The cmake could provide a function to generate source code via db  inspector and generate source code. This is not possible if this tool resides in a different repo

**Comment by fnc12** [comment]
Code gen is a good idea and you made it clear for me with your PR but has nothing common with this lib except include directives in the output. So it would be better to store it in a different repo.

**Comment by linux-fan-dave** [comment]
This is true. It does not share any code. I will go on and make it a repo myself then.

**Comment by linux-fan-dave** [comment]
If I would add an option which would enable the creation

**Comment by fnc12** [comment]
If we shall merge it than we need to make a lot of work before for:
1) fixing code style
2) adding opportunity for specifying type of getters/setter (there are 4 types of getters and 3 types of setters) and whether user wants to use public members instead of getters/setters
3) adding two more libs into this repo is a bad practice cause libs are being updated regularly and we need to sync them. It creates a package manager problem. I don't want to be a package manager and update this sources. Adding a package management software dependency will add more dependencies =) 

What I was thinking about is a code generator with a web interface where you type SQL, press `generate` and get a C++ code with this lib. E.g.: you type `SELECT *  FROM users WHERE id = 5` and get `auto rows = storage.get_all<User>(where(is_equal(&User::id, 5)));` 
or
`CREATE TABLE users (id integer not null primary key, name text not null)`
and get `make_table(make_column(&User::id, "id", primary_key()), make_column(&User::name, "name"));

Your idea can be a part of this service. One point: do you want your generator to be a part of a build pipeline or some kind of CLI tools you call manually when it is required to be called?

**Comment by linux-fan-dave** [comment]
I want to provide several template files. Some with getters/setters, some without. I could even provide some include files. The supper template contains a refernce to the correct setter template. The template directory is parameter now and could be freely configured to point to a user generated template files. I implemented this to be used from cmake. So a function needs to be exportet to allow users to generate the source files directly from a schema during build.

**Comment by linux-fan-dave** [comment]
The process could be devided into two subprocesses. 
- Inspect the Schema and generate a Json representation which can be passed to the template engine
- invoke the correct templates for every file to be generated and pass it the corresponding part of the json. The template renders the correct c++ code (style of getters / setters, namespaces, includes, base classes ....)
