### ISSUE TITLE
Way to make data members private?

### ISSUE THREAD

**Issue by abbygriffiths** [fnc12/sqlite_orm#4]
I'm guessing this will require quite some work, but is it possible to create a class or struct with private data members and persist it? Maybe pass a member function as a way to retrieve it? Or maybe declare a friend class inside the class or structure so that the private members can be made available? Seems like that'd be a really nice thing if implemented

**Comment by fnc12** [comment]
Of course I was thinking about it. Could you please show me a code of your data model classes for me to be clear - I'll see what can be done. Thanks

**Comment by abbygriffiths** [comment]
Sure, here you go. Nothing too crazy

```c++

class student
{
private: 
  // data members
  std::string name;
  short roll_no;
  std::vector<short> marks; // is this supported?

public:
  // getter member functions
  std::string get_name() const { return name; }
  short get_roll_no() const { return roll_no; }
  std::vector<short> get_marks() const { return marks; }

  student(const std::string name_,
          short roll_no_,
          const std::vector<short>& marks_):
    name(name_),
    roll_no(roll_no_),
    marks(marks_)
  {
    // maybe put some code here to provide access?
  }
  // or have a friend class in the definition?
};

```

Maybe we can pass the getter functions as a means of accessing it inside the make_storage function? Or put some code in the constructor or

**Comment by fnc12** [comment]
Ok thanks. It can be done very easy if there is a setter for every member mapped to the db. But class `student` hasn't it. So the only way is to construct a new one. By right now `sqlite_orm` doesn't support this kind of entities cause every member mapped to a storage supposed to be trivially constructible just like mapped classes themselves. 

About you comments inside a constructor and outside it: one of the main rules of the library is a single responsibility principle. So there won't be code in data model related to a storage. The reason is simple: there are a lot of libraries that strike through data model classes like json-, xml-, other mappers and parsers. These things can collide. That's why inserting sqlite storage rules inside data model is not quite smart. Also without `#include "sqlite_orm.h` in your data model classes they become more `modulable`. I mean you can just take your data model class and insert into another project and it will work event if this project doesn't have `sqlite_orm`.

If there were setters one can create a storage mapper with setter and getter function pointers instead of member pointers like this:

`make_column("name", student::get_name, student::set_name)`

I though of making of this things but I didn't cause if your setters and getters do nothing but settings and getting then your setters and getters are excess. This is just my opinion.

Also right now it is unable to construct an object by row with class constructor (as it is said in the `note` in readme class must have a default constructor. All fields fetched from db are assigned one by one during getting objects from a storage. So with such a class we can do nothing right now. But I'm going to create an update with non-trivially constructible classes support (just like yours).

About marks:

As I understood marks got to be stored in another table. I assume you expect a schema like this:
`CREATE TABLE students (id INTEGER, name TEXT, roll_no INTEGER)`
`CREATE TABLE marks (mark INTEGER, student_id INTEGER)`.

It means that marks supposed to be subentities inside `student` entity. Subentities are not supported cause subentities can led to infinite recursion of two entities from different table will have references to each other. That's why you have to get marks separately (but they can be assigned to a student object if you wish). I wrote an example code of how it can work right now:

```
class mark {
public:
    int value;
    int student_id;
};

class student{
public:
    int id;
    std::string name;
    int roll_no;
    std::vector<mark> marks;
};

decltype(student::id) mikeId;
decltype(student::id) annaId;

using namespace sqlite_orm;
auto storage = make_storage("students.sqlite",
                            make_table("students",
                                       make_column("id",
                                                   &student::id,
                                                   primary_key()),
                                       make_column("name",
                                                   &student::name),
                                       make_column("roll_no",
                                                   &student::roll_no)),
                            make_table("marks",
                                       make_column("mark",
                                                   &mark::value),
                                       make_column("student_id",
                                                   &mark::student_id)));
{
    storage.sync_schema();    // create tables if they don't exist
    student mike{ -1, "Mike", 123 };    //  create student named `Mike` without marks and without id
    mike.id = storage.insert(mike); //  now Mike has id, let's assign marks {3, 4, 5} to him and save them to the storage
    mikeId = mike.id;   //  for future use
    mike.marks = { { 3, mike.id }, { 4, mike.id }, { 5, mike.id } };
    //  call transaction to make several inserts at once..
    storage.transaction([&]{
        for(auto &m : mike.marks) {
            storage.insert(m);
        }
        return true;
    });
    
    //  also let's create another students with marks..
    student anna{ -1, "Anna", 555 };
    anna.id = storage.insert(anna);
    annaId = anna.id;
    anna.marks.push_back(mark{ 6, anna.id });
    anna.marks.push_back(mark{ 7, anna.id });
    storage.transaction([&]{
        for(auto &m : anna.marks) {
            storage.insert(m);
        }
        return true;
    });
}

// now let's assume we forgot about object `mike`, let's try to get him with his marks
//  assume we know `mikeId` variable only

{
    auto mike = storage.get<student>(mikeId);
    cout << "mike = " << storage.dump(mike) << endl;
    
    //  to get all marks we must execute `SELECT * FROM marks WHERE student_id = mikeId`
    mike.marks = storage.get_all<mark>(where(is_equal(&mark::student_id, mike.id)));
    
    cout << "mike.marks = ";
    for(auto &m : mike.marks) {
        cout << m.value << " ";
    }
    cout << endl;
    
    auto anna = storage.get<student>(annaId);
    cout << "anna = " << storage.dump(anna) << endl;
    anna.marks = storage.get_all<mark>(where(is_equal(&mark::student_id, anna.id)));
    cout << "anna.marks = ";
    for(auto &m : anna.marks) {
        cout << m.value << " ";
    }
    cout << endl;
}
```

It can be more complicated that you expected but the goal of the lib is to understand how it works inside sqlite. To select a single student you have to execute two queries:
* `SELECT * FROM students WHERE id = ?`
* `SELECT * FROM marks WHERE student_id = ?`

And you call two functions here for this:
* `auto mike = storage.get<student>(mikeId);`
* `mike.marks = storage.get_all<mark>(where(is_equal(&mark::student_id, mike.id)));`

Also please stay subscribed to receive an email notification once non-trivial constructible data classes support appears. Please feel free to ask whatever you want and good luck with `sqlite_orm`.

**Comment by fnc12** [comment]
Also if you need your student objects to be immutable in your code just add `const` in front of their definition once you obtained all the data from the storage - it will prevent any assignment to the objects without privacy of members.

**Comment by abbygriffiths** [comment]
Ah thanks so much! Really cool work. Eager to see how the project develops with time. It's really difficult to get a decent ORM for C++, much less one that does it with STL constructs. Kudos to you for the framework and for taking the time to give these examples as well 😄 👍

**Comment by fnc12** [comment]
Thanks man. Also I just realized that your code can be even more simple - we can replace `std::vector<mark>` with `std::vector<int>` as you planned initially and use raw select to extract only mark values into vector:

```
class mark {
public:
    int value;
    int student_id;
};

class student{
public:
    int id;
    std::string name;
    int roll_no;
    std::vector<decltype(mark::value)> marks;
};

decltype(student::id) mikeId;
decltype(student::id) annaId;

using namespace sqlite_orm;
auto storage = make_storage("students.sqlite",
                            make_table("students",
                                       make_column("id",
                                                   &student::id,
                                                   primary_key()),
                                       make_column("name",
                                                   &student::name),
                                       make_column("roll_no",
                                                   &student::roll_no)),
                            make_table("marks",
                                       make_column("mark",
                                                   &mark::value),
                                       make_column("student_id",
                                                   &mark::student_id)));
{
    storage.sync_schema();    // create tables if they don't exist
    student mike{ -1, "Mike", 123 };    //  create student named `Mike` without marks and without id
    mike.id = storage.insert(mike); //  now Mike has id, let's assign marks {3, 4, 5} to him and save them to the storage
    mikeId = mike.id;   //  for future use
    mike.marks = { 3, 4, 5 };
    //  call transaction to make several inserts at once..
    storage.transaction([&]{
        for(auto &m : mike.marks) {
            storage.insert(mark{m, mike.id});
        }
        return true;
    });
    
    //  also let's create another students with marks..
    student anna{ -1, "Anna", 555 };
    anna.id = storage.insert(anna);
    annaId = anna.id;
    anna.marks.push_back(6);
    anna.marks.push_back(7);
    storage.transaction([&]{
        for(auto &m : anna.marks) {
            storage.insert(mark{m, anna.id});
        }
        return true;
    });
}

// now let's assume we forgot about object `mike`, let's try to get him with his marks
//  assume we know `mikeId` variable only

{
    auto mike = storage.get<student>(mikeId);
    cout << "mike = " << storage.dump(mike) << endl;
    
    //  to get all marks we must execute `SELECT * FROM marks WHERE student_id = mikeId`
    mike.marks = storage.select(&mark::value, where(is_equal(&mark::student_id, mike.id)));
    
    cout << "mike.marks = ";
    for(auto &m : mike.marks) {
        cout << m << " ";
    }
    cout << endl;
    
    auto anna = storage.get<student>(annaId);
    cout << "anna = " << storage.dump(anna) << endl;
    anna.marks = storage.select(&mark::value, where(is_equal(&mark::student_id, anna.id)));
    cout << "anna.marks = ";
    for(auto &m : anna.marks) {
        cout << m << " ";
    }
    cout << endl;
}
```
