### ISSUE TITLE
std::vector<std::string> class member

### ISSUE THREAD

**Issue by Ninja-007** [fnc12/sqlite_orm#45]
class Vect
{
std::vector<std::string> _Vec;
};

decltype(auto) GetStorage() 
{
    return make_storage( "Vector",
                        make_table("vec",
                                   make_column("R", &Vect::_Vec)
                                   )
                        );
}

How to store and restore std::vector in and from database?

**Comment by fnc12** [comment]
This is a good question. First you have to decide how would you store it without `sqlite_orm` but with pure `sqlite3`. The problem is that there is no `string array` type in sqlite or `varray` just like Oracle DB has. Please check a question [here](https://stackoverflow.com/questions/9053685/android-sqlite-saving-string-array). But you have two options to do a trick.
1) Store string in a different table with id foreign key per every string. Something similar can be found in [subentities.cpp example](https://github.com/fnc12/sqlite_orm/blob/master/examples/subentities.cpp)
2) Serialize string array somehow on insert. In JSON probably. Parse it on select. There is a very comfortable json lib [here](https://github.com/nlohmann/json).

**Comment by Ninja-007** [comment]
Thanks,
I am planning to store it as comma separated strings.
