### ISSUE TITLE
Use "where" on child struct failed

### ISSUE THREAD

**Issue by 305236917** [fnc12/sqlite_orm#635]
```c++
struct A
{
	int Id;
	string Name;
};

struct B : A
{
	string Extern;
};

auto ts = 
		make_storage("Storage.db",
			make_table("BT",
				make_column("Id", &B::Id, primary_key()),
				make_column("Name", &B::Name),
				make_column("Extern", &B::Extern)
			)
		);

auto bs = ts.get_all<B>(sqlite_orm::where(is_equal(&B::Name, "B")));  //Compiled failed

//struct A
//{
//	int Id;
//	string Name;
//};

struct B
{	
        int Id;
	string Name;
	string Extern;
};

auto ts = 
		make_storage("Storage.db",
			make_table("BT",
				make_column("Id", &B::Id, primary_key()),
				make_column("Name", &B::Name),
				make_column("Extern", &B::Extern)
			)
		);

auto bs = ts.get_all<B>(sqlite_orm::where(is_equal(&B::Name, "B")));  //Compiled successful
```

**Comment by fnc12** [comment]
the reason is that you use inheritance. Storage maps one table to one class. To understand a class to map it takes the first member pointer from `make_table` call and deduces a type from it. Your first member pointer is `&B::Id`. Its type is `B` but actually it is declared inside `A`. So compiler thinks that you mean `A` and `A` is not mapped to your storage so static check fails. This is how C++ works and I cannot change it unfortunately. So first you need to change the declaration of your storage with explicit mapped type:
```c++
auto ts = 
		make_storage("Storage.db",
			make_table<B>("BT",    // <=== consider a template argument here
				make_column("Id", &B::Id, primary_key()),
				make_column("Name", &B::Name),
				make_column("Extern", &B::Extern)
			)
		);
```
Next when you need to reference a B's member which is actually declared inside `A` or other its' superclass use `column<B>(&B::Name)` instead of `&B::Name` like this:

```c++
auto bs = ts.get_all<B>(sqlite_orm::where(is_equal(column<B>(&B::Name), "B")));
```
But using `column` function is not required for `Extern` member cause it is declared inside `B` and compiler will understand it.

**Comment by 305236917** [comment]
I appreciate your time. Now it works.

**Comment by fnc12** [comment]
you are welcome. Please feel free to ask anything. Also don't forget to looks for the same issue first - it will take less your time.
