### ISSUE TITLE
More progressive enum binding?

### ISSUE THREAD

**Issue by denzor200** [fnc12/sqlite_orm#660]
Why is enum binding so verbose? Is there any objective reason why we can't implement this?
```c++
enum class Gender {
  Male,
  Female,
};

struct SuperHero {
  int id;
  std::string name;
  Gender gender;
};

auto storage =
    make_storage("db.sqlite",
                 make_enum(make_value("male", Gender::Male),
                           make_value("female", Gender::Female)),
                 make_table("superheros", ///
                            make_column("id", &SuperHero::id, primary_key()),
                            make_column("name", &SuperHero::name),
                            make_column("gender", &SuperHero::gender)));
```

**Comment by fnc12** [comment]
Cause different people store enums in different ways. Most populars ways are:
1) as string (as you don in this example)
2) as int

Also enum may be nullable - some people do it. Of source API simplifying is a very good idea and your code looks very pretty but first of all we must not  create limits and make people omit using `sqlite_orm` due to its limitations.

**Comment by denzor200** [comment]
We do not plan to limit anyone in anything. Those who have a difficult case use **the old API**. Those who just need to save the enum as a string - just use **the new API** and don't bother.

**Comment by fnc12** [comment]
Ok it sounds good. But the question remains about implementation. The old way is made with template specialization which works for all storages within a binary. The new way omits any specializations and adds reflection right into a storage. This is cool. But we will need to implement the second API and support both ways. Also what happens when someone will add both specializations and the new way of implementation? And how it all will be implemented?

**Comment by denzor200** [comment]
> Also what happens when someone will add both specializations and the new way of implementation?
we need to think about how to act correctly in this situation
> And how it all will be implemented?
I'm willing to take the time and figure out the details

**Comment by fnc12** [comment]
@denzor200 thank you. Your ideas are great!

**Comment by denzor200** [comment]
> Also what happens when someone will add both specializations and the new way of implementation?

Let's imagine, that the "Gender" enum was bound by old way with template specialization. 
And then, this code will throw build error:
```
make_enum(
     make_value("male", Gender::Male),
     make_value("female", Gender::Female)) ///< error: Can't make enum, this enum was already bound with template specialization. 
```
No panic, just add 'override_specialization' tag:
```
make_enum(
	make_value("male", Gender::Male),
	make_value("female", Gender::Female)).override_specialization() ///< OK

```
How do you think about this?

**Comment by fnc12** [comment]
That is nice. Or we can just skip `override_specialization` and treat `make_enum` presence as intent to override specialization for this storage and reverse: is there is no `make_enum` then specialization is used. 
Also `make_enum` can accept any type not only string. Event `std::nullptr_t`. It will solve nullable enum problem also.

**Comment by fnc12** [comment]
@denzor200 enum serialization is not going to change in the nearest future so I am closing this issue. Please reopen once you need it
