### ISSUE TITLE
Don't  understand static_assert in func<class F, class ...Args> 

### ISSUE THREAD

**Issue by juandent** [fnc12/sqlite_orm#769]
The static_assert in the following code below is of the form A && ! B || B, where:

```C++
A = argsCount == functionArgsCount 
B = std::is_same<function_args_tuple, std::tuple<arg_values>>::value
```

Can you please elaborate? It seems to me that assert should fail if argsCount != functionArgsCount...

```C++
 template<class F, class... Args>
    internal::function_call<F, Args...> func(Args... args) {
        using args_tuple = std::tuple<Args...>;
        using function_args_tuple = typename internal::callable_arguments<F>::args_tuple;
        constexpr auto argsCount = std::tuple_size<args_tuple>::value;
        constexpr auto functionArgsCount = std::tuple_size<function_args_tuple>::value;
        static_assert(
            (argsCount == functionArgsCount && !std::is_same<function_args_tuple, std::tuple<arg_values>>::value) ||
                std::is_same<function_args_tuple, std::tuple<arg_values>>::value,
            "Arguments amount does not match");
        return {std::make_tuple(std::forward<Args>(args)...)};
    }
```

thanks!
Juan Dent

**Comment by fnc12** [comment]
```
if argsCount == functionArgsCount then
    everything is ok
else if args == std::tuple<arg_values> then
    everything is ok
else
    fail
endif
```
The first case happens when user calls a function with static amount of arguments.
The second case happens when user calls a function with dynamic amount of arguments. In this case `argsCount != functionArgsCount` may happen cause one can put any number of args into `func<T>(...)` call but arguments count in function class is 1 and it is `arg_values`.
All other cases mean that amount does not equal arguments count and function is not dynamic. So if you make a function like `INITCAP(X, Y)` and call it with three arguments you'll get a compile time error.

**Comment by juandent** [comment]
Got it thank you very much!
