### ISSUE TITLE
Updating an item retrived with `get_pointer()`

### ISSUE THREAD

**Issue by define-private-public** [fnc12/sqlite_orm#797]
I'm not always a fan of having to do exception handling.  So I like using that `get_pointer()` method.  I did this in my code:

```c++
auto todo = db.get_pointer<TodoItem>(todo_id);
if (todo) {
...
```

Inside the `if` block, I tried to do `db.update(todo)`, but it failed to compile.  Then when I did `db.update(*todo)` it compiled fine.

I think it would be much more programmer friendly if the `update()` method could also accept in the pointers that are made with `get_pointer()`, instead of having to also dereference it too.

**Comment by fnc12** [comment]
No cause if function can accept a pointer then it needs to know what to do if this pointer is null. This is not a scenario for SQLite. Dereferencing an object to pass to a database is responsibility of a client (you) cause you use pointers instead of strict values (and it costs adding only one character in your code). If you don't like writing `*` inside every update call then you can write your own function for update and use it instead:
```c++
template<class T, class S>
void updateObject(const std::unique_ptr<T> &pointer, S &storage) {
    storage.update(*pointer);
}
///.....

updateObject(todo, db);
```

**Comment by define-private-public** [comment]
Okay, fair enough.  I'll close the issue.
