### ISSUE TITLE
Made a sample app

### ISSUE THREAD

**Issue by define-private-public** [fnc12/sqlite_orm#808]
https://gitlab.com/define-private-public/sqlite_orm_todo_sample

Right now I'm working on a much larger app, but I wanted to take some time to better learn how to use SQLite ORM (e.g. "how would I do a data migration?").  So I spent some time making a sample application.  It's a very simple command line TODO list.

If you have any suggestions on how to make this a better sample for others, or design/architectural patterns that should be used instead I'm open to suggestions.  If you think it might also be good for other users to look at, I would appreciate a link to it in the README.  I'll be sure to keep this project up to date to match any changes in SQLite ORM.

**Comment by fnc12** [comment]
That is nice. Let me add some comments:
1) using a sequence `autoincrement(), primary_key()` is legacy and will be removed at v1.8. Better write `primary_key(), autoincrement()` instead. Later it will be refactored to `primary_key().autoincrement()` but not right now;
2) it is better to serialize enum using built in `sqlite_orm` way just like it is implemented in [`enum_binding` example](https://github.com/fnc12/sqlite_orm/blob/master/examples/enum_binding.cpp) just because it reduces amount of `static_cast`s in your code. Example shows string binding but you can make int binding the same way. But it is up to you;
3) `const string quit_cmd("quit");` can be refactored to `const string_view quit_cmd("quit");` to reduce heap allocations;
4) migration code which uses `insert` with `update_all` can be changed using one `replace` or raw `insert` query:
```c++
const V2::TodoItemRecord new_todo{
    .id     = old_todo.id,
    .who_id = who_id,
    .thing  = old_todo.thing,
    .status = status_v1_to_v2(old_todo.status)
};
db.replace(new_todo);
```
or
```c++
const V2::TodoItemRecord new_todo{
    .id     = old_todo.id,
    .who_id = who_id,
    .thing  = old_todo.thing,
    .status = status_v1_to_v2(old_todo.status)
};
db.insert(into<TodoItemRecord>(), 
          columns(&V2::TodoItemRecord::id, &V2::TodoItemRecord::who_id, &V2::TodoItemRecord::thing, &V2::TodoItemRecord::status), 
          values(new_todo.id, new_todo.who_id, new_todo.thing, new_todo.status));
```

**Comment by define-private-public** [comment]
1. Thanks for the heads up.  Done.
2. I actually did that for V2.  Take a look: https://gitlab.com/define-private-public/sqlite_orm_todo_sample/-/blob/7f15127a9d419394eec91f9e8c1103310fa2101b/src_v2/Data/V2/StatusEnum_sqliteorm_serialize.h
3. I'm aware of `string_view`.  I just wanted to keep things simple at the moment
4. Thanks!  I was wondering if there was a way to do that with one DB operation.
